### ISSUE TITLE
Error metaAsArray:true + multipleStatements: true

### ISSUE THREAD

**Issue by zirill** [mariadb-corporation/mariadb-connector-nodejs#106]
```
CREATE TABLE t (i int);
INSERT INTO t(i) VALUES (1);
SELECT i, i FROM t;
```
Bug 1) if metaAsArray = true, multipleStatements - error

Bug 2) columns name: dentical columns merge

**Comment by rusher** [comment]
Thanks for reporting about the identical column issue, I did see that for first alpha implementation, but at that time it was at least to have the same functionnality as other drivers, ... and forgot since that time. 

Commit https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/5fb69cb382801c953566651ca8e54381d148980d solve this issue. 
Now an Error is thrown when that occur. 

After that, user will have different solution to solve that, easiest one is to use alias, like : 
`SELECT i, i as i2 FROM t;`

Could you develop what do you mean for bug 1 ?

**Comment by zirill** [comment]
```
createPool({metaAsArray:true, multipleStatements: true,

      const a = await conn.query({sql:
            "DROP TABLE IF EXISTS t; " +
            "CREATE TABLE t (i int);\n" +
            "INSERT INTO t(i) VALUES (1);\n" +
            "SELECT i FROM t; "
         , timeout: 3000});

```

> /node_modules/mariadb/lib/cmd/resultset.js:348
>           this._meta[this._responseIndex] = this._columns;
> TypeError: Cannot set property '3' of undefined

**Comment by rusher** [comment]
btw, https://github.com/mariadb-corporation/mariadb-connector-nodejs/commit/5fb69cb382801c953566651ca8e54381d148980d solve duplicate field merge. 
Now an error is thrown if a field will be merged (This can be disabled with option `checkDuplicate` for compatibility)
