### ISSUE TITLE
Log resulting query after placeholers substitution

### ISSUE THREAD

**Issue by whitebyte** [mariadb-corporation/mariadb-connector-nodejs#133]
Is there any way to log the final query once the `query` function done processing a query string and replacements? I mean, I cal log a query string and replacements separately, like

```sql
[log 1] SELECT * FROM users u WHERE u.id = ?
[log 2] Replacements: [ 123 ]
```
, but don't see any way to get 
```sql
SELECT * FROM users u WHERE u.id = 123
```
in my logs

**Comment by rusher** [comment]
Sorry, but not possible. 
MariaDB connector tries to avoid creating any unnecessary buffer. So, SQL command is never represented at any moment in memory.  
to explain with one example : 
```
    https.get('https://someContent', readableStream => {
        //readableStream implement Readable, driver will stream data to database 
        connection.query("INSERT INTO myTable VALUE (?)", [readableStream]);
    });
```

To simplify, the driver will send to socket escaped 'INSERT INTO myTable VALUE (' , then escaped chunks of readableStream, then ')'.

If you need that possibility, check mysql or mysql2 library. They might have this possibility because they create a string buffer containing the entire SQL command before sending it to the server.

**Comment by whitebyte** [comment]
Actually I'm migrating from mysql2. So if it's by design, feel free to close.
