### ISSUE TITLE
Help if getConnection "parallel"?

### ISSUE THREAD

**Issue by BonsoirDiep** [mariadb-corporation/mariadb-connector-nodejs#140]
### I run my "test" function with "async" (caolan) funtion parallel. And detect error "ER_GET_CONNECTION_TIMEOUT".
I decided to try again with "setTimeout", i want to get result (**important**)
When i increase "connectionLimit", or decrease "connectTimeout", main funtion "test" not faster.
```js
/*
my table "images" (of database "app") ~ 621359 rows
  | 1 | _id | int(11) | AUTO_INCREMENT (*primary key)
  | 2 |  keyme | text | utf8_general_ci
  | 3 | image |text  | utf8_general_ci
*/

const PAUSE_TIME=0, BUGTIME2= 0;
var sql = 'select _id, image from app.images where keyme= ?', vals= ['test-123456'];
var mariadbQuery= 0;

var releaseStt= 0;
const pool = mariadb.createPool({
    socketPath: '/var/lib/mysql/mysql.sock',
    user: 'root',
    password: 'test123456',
    // acquireTimeout: 4000,
    // connectTimeout: 3000,
    // multipleStatements: true,
    // leakDetectionTimeout: 10000,
    connectionLimit: 5,
    // maxAllowedPacket: 1024*1024*100,
    debug: false,
    // checkDuplicate: false,
    // compress: true,
    // idleTimeout: queryTimeout
}).on('release', function(){
    // console.log('release', releaseStt++);
});
function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
var minRnd= 20, maxRnd= 90;
function get4(cbx, stt){
    stt= stt || 0;
    if(stt>999 && PAUSE_TIME) {
        cbx(0);
        return;
    }
    pool.getConnection().then(function (conn) {
        // console.info("connected ! connection id is " + conn.threadId);
        function cb(dataX, x){
            if(BUGTIME2) console.timeEnd(x);
            cbx(dataX);
        }
        var x= '>query_'+ (mariadbQuery++);
        if(BUGTIME2) console.time(x);
        conn.query({
            sql
        }, vals)
        .then((data) => {
            conn.end();
            if(data[0]) {
                cb(1, x);
            } else cb(0, x);
        })
        .catch(err2 => {
            conn.end();
            cb(0, x);
        })
    }).catch(function (err) {
        if (err && err.code == 'ER_GET_CONNECTION_TIMEOUT') {
            // Error: retrieve connection from pool timeout after ~acquireTimeout
            setTimeout(function () {
                get4(cbx, stt+1);
            }, getRandomInt(minRnd, maxRnd));
            return;
        }
        console.error("not connected due to error: " + err);
        cbx(0);
    });
}

var queryDone= 0;
function test(maxMe){
    queryDone= 0;
    var arrFn= [];
    var xMax= maxMe || 1;
    if(xMax<1) xMax= 1;
    for(var i=0; i< xMax; i++){
        arrFn.push(function(callback) {
            get4(function(str){
                if(str) queryDone++;
                callback(null, str);
            });
        });
    }
    console.time('caolan_test');
    require('async').parallel(arrFn, function(err, results) {
        console.timeEnd('caolan_test');
        console.log(`#done# ${queryDone}/${xMax}`)
    });
}
test(50);
```
### results: ~22s
```txt
...
>query_46: 2168.257ms
>query_48: 2067.725ms
>query_49: 2040.181ms
>query_47: 2098.927ms
caolan_test: 21698.709ms
#done# 50/50
```

### I build my web app
1 request with query Id => 1 connection query from datase => send user.
If i have >50 request at the same time? How fast?

**Comment by rusher** [comment]
The option you want is probably `acquireTimeout` (default is 10000ms)

The test you run is kind of incomplete: it is run without waiting for pool to fill connections.
Your main problem here is that query takes too much time, obviously because not using index, but that permit to describe how pool works : 

If you launch execute 50 times the function in parallel with a pool with 5 connections, that will mean that 5 functions will run in parallel: Node has only one thread, ok, but queries will be sent to database server one by one in a fraction of time, then wait for each connection result. Other 45 launched functions will wait for a connection to be freed in pool. 
So after a time (around 2100ms from your example), 5 functions will ended successfully, 5 others will begin because having a connection from pool, 40 will be still in queue. 

Option `acquireTimeout` might be important, because if queuing in pool, waiting for connection and reaching `acquireTimeout` timeout, an error "Error: retrieve connection from pool timeout after XXms" will be thrown.

connectionLimit is usually better low (around 2x the number of cpu). Having more connection will only make server switching thread more often. connectTimeout option is to limit the time for connection creation, mainly to throw an error if there is a network issue that cause connection to take too much time.

**Comment by BonsoirDiep** [comment]
"Your main problem here is that query takes too much time, obviously because not using index". This is problem.

I use other database for creat Index { keyme }
