### ISSUE TITLE
Double question mark

### ISSUE THREAD

**Issue by shockdevv** [mariadb-corporation/mariadb-connector-nodejs#146]
`
await pool.query("UPDATE businesses SET ?? = ? WHERE ID = ?", [fieldName, value, id]);
`

is that actually possible? if not, is there a better way to do that? thanks.

**Comment by rusher** [comment]
Using double question mark isn't possible. 
The reason is that this is not possible to use binary protocol with that kind of query without parsing command client side. 
Goal is to prevent having client parsing command for performance reason. 

Still that can be achieved using [connection.escapeId](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionescapeidvalue--string)

like : 

`await pool.query("UPDATE businesses SET ? = ? WHERE ID = ?", [pool.escapeId(fieldName), value, id]);`

or using template literals:

`await pool.query("UPDATE businesses SET ${pool.escapeId(fieldName)} = ? WHERE ID = ?", [value, id]);`
