### ISSUE TITLE
Reporting the wrong node version and crashing program 

### ISSUE THREAD

**Issue by NathanR1225** [mariadb-corporation/mariadb-connector-nodejs#151]
When I add mariadb to my project it throws a "mariadb requires at least version  10.13 of Node, please upgrade" error I am currently running Node 15.11.0 and have tried 14.16.0 and get the same result.  It then throws a "index.js:22 Uncaught TypeError: process.exit is not a function" from the pleaseUpgradeNode package. 
![node_and_exit](https://user-images.githubusercontent.com/63110047/111534688-8469d480-8725-11eb-9a38-9d0984f39d5a.PNG)
![node](https://user-images.githubusercontent.com/63110047/111534806-a2cfd000-8725-11eb-8a29-b51233138095.PNG)

If I comment out the line in pleaseUpgradeNode  that is causing the error to crash.  I then get a "connection failed TypeError: Net.connect is not a function" error every time I try to establish a connection. 
![net](https://user-images.githubusercontent.com/63110047/111534527-54223600-8725-11eb-96ad-4fe466acfb33.PNG)

Any help would be appreciated.

**Comment by rusher** [comment]
That's strange, the function [net.connect(port[, host][, connectListener])](https://nodejs.org/api/net.html#net_net_connect_port_host_connectlistener) that connector use has been added in node.js in version v0.1.90. 
If not present, that means the Node.js version used is a very old one, and "mariadb requires at least version 10.13 of Node, please upgrade" message seem accurate. 

Can you print node.js version at runtime with something like `console.log(process.version);` ?
process.version exists since v0.1.3, so this will permit to confirm the version of  node.js used at runtime.

**Comment by NathanR1225** [comment]
the command runs but returns a blank value. I create a new react project to see if it was something in my current project but same result. If I run console.log(process.versions); it comes back with an empty object.

**Comment by rusher** [comment]
`process.version` not `process.versions` , process.versions only exists since v0.2.0, so since net.connect doesn't exists (and created in v0.1.90), i suspect some very old node version before v0.1.90

**Comment by NathanR1225** [comment]
I ran both logs after some googling. I will have to look more into it because this is a fresh install of windows and has only had v14 and up on it. Maybe I will just uninstall all node and just put NVM on this machine.

**Comment by NathanR1225** [comment]
We were able to figure out what happened. We were trying to connect from react to Mariadb directly with out a node process in between. It turns out you can not call a node process in the web browser it throws the errors above. We are now implementing an API that is running in node.
