### ISSUE TITLE
Escaping query values vs mysql/mysql2

### ISSUE THREAD

**Issue by tomcon** [mariadb-corporation/mariadb-connector-nodejs#155]
This is great work, very impressive!

Can't seem to find support for this in the documentation, can you confirm it is not currently covered?
If so, any eta when it might be? Handy for dev especially. Thanks

https://github.com/mysqljs/mysql#performing-queries
```
This escaping allows you to do neat things like this:

var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```

**Comment by rusher** [comment]
This is indeed one of the rare differences compare to mysql connector.

There is different reason for that : 
a minor annoyance is that since there can be JSON collumns and JSON object can be passed as parameter, this can be confusing. But the real reason for that is question mark must correspond to some string or literal possible, following SQL standard.
This will permit (with the future MariaDB 10.6 server that will be GA in a few month) further enhancement like caching, avoiding metadata network exchanges, ...
permitting to gain up to 60% performance (depending on queries). And this can be achieved only keeping API this way. 

So this means keeping code like this : 
```
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET `id` = ?, `title` = ?', [post.id, post.title], function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
```
It's a little less handy, but a minor annoyance comparing to very fast performance is always a better choice.

**Comment by tomcon** [comment]
Sure, a lot less handy @rusher  : ) but agree very fast performance better

This is a start of a replacement for dev in case of interest/helpful to anyone:

```
    let opts = getQueryOptions( sql, rowsAsArray, values)
    let rs = await pool.query(opts)   // will automatically release connection


function getQueryOptions(sql, rowsAsArray, values){
  const setq = ' set ? '
  const sqltest = sql.toLowerCase()
  let adjust = sqltest.indexOf(setq) 

  // single array element with an object of params?
  if (adjust && isObject(values)) {
    let insert = sqltest.indexOf('insert ') > -1 

    // can adjust js vals to sql vals here as necessary
    let s = ' set '
    Object.keys(values).forEach( e => {

      // convert to null?
      if (values[e] === null || values[e] === undefined){
        s += `${e}=NULL,` 
      }
      else {
        s += `${e}='${values[e]}',` 
      }
    })

    s = s.slice(0,-1) + ' '           // lose last ,
    sql = sql.replace( setq, s )      // replace ? with values

    // hacking sanity check
    if (!insert){
      let whereclause = sql.indexOf(' where ') > -1 
      if (!whereclause){
        // prevent 
        sql = 'MISSING WHERE CLAUSE IN UPDATE!'
      }
    }
    values = null
    console.log( 'generated sql: ', sql )
  }
  return {sql, rowsAsArray, values}
}
```

**Comment by tomcon** [comment]
@rusher one small change is that the mysql/mysql2 driver return a ResultSetHeader vs OkPacket from rowsAsArray
so I'm now using this (see below, always return a recordset (rs) + meta if available. 
It seems to cover all cases, can you confirm please?
```
    rs = await pool.query(opts)   // will automatically release connection
    if (rs) {

      if (rs.meta){                 // select
        meta=rs.meta
        delete rs.meta
      }
      else if (isObject(rs)){       // insert/update/delete
        meta=rs
        rs=null
      }
      else if (rs && rs.length ===2 && rs[1].affectedRows !== undefined){   // rowsAsArray, call sp, etc
        meta=rs[1] 
        rs=rs[0] 
      }
    }
```

**Comment by rusher** [comment]
I don't really follow your last if. 

That depends what you want to achieve. 

A resultset format with standard option is: 
* an OkPacket
* an array of rows + meta

But there can be multiple resultset (that is possible stored procedures or when enabling `multipleStatements`)
Then query result can then be an array of resultset

If you want to be complete, then there is other option to be taken care of : 
* `rowsAsArray` option, row format is not a JSON object, but an array. 
* `nestTables` will return a JSON object separated by table identifier.

**Comment by tomcon** [comment]
Thanks @rusher, for completeness and reminding about multiple resultsets

> I don't really follow your last if.
That's a check for your second last line in your reply
> rowsAsArray option, row format is not a JSON object, but an array.
i.e. Array(2) [Array(1), OkPacket]

**Comment by tomcon** [comment]
@rusher came across this earlier, looks like the driver does support it after all.  

Quick test seems to confirm, if so then it's good news on one hand but sadly a disappointing waste of my time also

https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/connection-options.md
```
permitSetMultiParamEntries 

 Compatibility option to permit setting multiple value by a JSON object to replace one question mark. key values will replace the question mark with format like key1=val,key2='val2'. Since it doesn't respect the usual prepared statement format that one value is for one question mark, this can lead to incomprehension, even if badly use to possible injection.
```

**Comment by tomcon** [comment]
> I think there was a way to see the generated sql in mysql/mysql2, it is possible here would you know?

**Comment by rusher** [comment]
mysql/mysql2 parse query, then recreate multiple string until having definitive command to send to socket, so i imagine that there is some option to log generated value. 

mariadb driver implementation differ. When parsing query, parts and parameter are directly written in buffer pool, then send to socket by packet up to 16Mb. So that's globally similar for small queries but permit limiting memory use up to 16Mb maximum.
Since there is no generated string, it cannot be logged.

If this is only for debug, you can enable trace network exchanges enabling option `debug`. 
Then you will see on console trace like that : 
```
==> conn:61 Query(0,13)
+--------------------------------------------------+
|  0  1  2  3  4  5  6  7   8  9  a  b  c  d  e  f |
+--------------------------------------------------+------------------+
| 09 00 00 00 03 53 45 4C  45 43 54 20 31          | .....SELECT 1    |
+--------------------------------------------------+------------------+
```
(this can be enable at runtime too with `connection.debug(true);`)
