### ISSUE TITLE
Supported dbs

### ISSUE THREAD

**Issue by coolmonster** [mariadb-corporation/mariadb-connector-nodejs#158]
What are the supported databases using MariaDB connector?

**Comment by Turbine1991** [comment]
It might be better to ask if it'll work for any database in particular. MariaDB is effectively compatible with MySQL and forks.

**Comment by rusher** [comment]
Driver is compatible with all MariaDB and MySQL **supported** servers.

Supported version = 
* MariaDB 10.2 -> 10.6 
* MySQL 5.7 -> 8.0

MariaDB 5.5, 10.0 and 10.1 are EOL recently, MySQL 5.5 and 5.6 either. 

In fact driver is actually compatible with all servers version, not just supported one, but is tested only with supported servers. 
So that means, some modifications in the future might remove compatibility with old servers.

**Comment by rusher** [comment]
closing, since answered.

Feel free to create a new conversation linking to this one if that's not the case !
