### ISSUE TITLE
Timezone offset is -2 from UTC instead of +2 using IANA in connector settings

### ISSUE THREAD

**Issue by classic0** [mariadb-corporation/mariadb-connector-nodejs#184]
**node --version** 
``v14.17.3``
**Connector**
``"mariadb": "^2.5.5"``
**mariadb --version**
``mariadb  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2``

**SELECT @@system_time_zone;**
``EET``
**SELECT @@global.time_zone;**
``UTC``

**Column definition**
``created_at datetime NOT NULL DEFAULT current_timestamp()``

**Instantiating connector by:**
``const pool = mariadb.createPool({ 
    ...getMariaDbOptions(process.platform),
    timezone: 'Europe/Tallinn',
});``

**Selecting created_at from msyql shell**
``"2021-12-02 07:22:34"``

**Selecting created_at thru connector**
``"2021-12-02T05:22:34.000Z"``

Estonia is 2 hours ahead of Coordinated Universal Time.

--

Setting the timezone: 'local' yields equal result as the IANA tz.
Setting the timezone: 'auto' yields the unchanged UTC datetime.
Setting the timezone: '-02:00' yields +2 to the UTC. 

So oddly it seems to be in reverse due to some conditon.

Nodejs is initialized with TZ=Europe/Tallinn process.env.

**Comment by rusher** [comment]
Not sure what is the issue here. for Europe/Tallinn : 2021-12-02 07:22:34 = 2021-12-02T05:22:34.000Z  (Z stands for Zero offset = UTC )
You'll tell if i guess wrong:  
I guess that the 
'-2:00' = 'Etc/GMT-2'  

I guess that this is the etc/GMT-2 that correspond to inverted offsets that are the issue 
```
    console.log(moment.tz('etc/GMT-2').format('YYYY-MM-DD HH:mm ZZ'));
    // 2021-12-13 16:26 +0200
    console.log(moment.tz('Europe/Tallinn').format('YYYY-MM-DD HH:mm ZZ'));
    // 2021-12-13 16:26 +0200

```
see https://momentjs.com/timezone/docs/#/zone-object/offset/ for the reason why. 
(and why locality based identifiers are always prefered).

**Comment by rusher** [comment]
closing since no answer since 1 year
