### ISSUE TITLE
ER_MAX_PREPARED_STMT_COUNT_REACHED in batch inserts

### ISSUE THREAD

**Issue by webigorkiev** [mariadb-corporation/mariadb-connector-nodejs#207]
Hello

mariadb@3.0.1

When i use batch inserts or pool.batch 
growing 
Com_stmt_prepare
but 
Com_stmt_close  = 0

And then i get ER_MAX_PREPARED_STMT_COUNT_REACHED error

mariadb@2.5.6

This does not appear

Thanks

**Comment by webigorkiev** [comment]
Workaround

prepareCacheLength: 0

**Comment by rusher** [comment]
found the issue. Problem reside in prepare cache that doesn't execute close immediatly, resulting in having more cached prepare than `prepareCacheLength`

**Comment by rusher** [comment]
Current implementation use @alloc/quick-lru that evict previous cache by bulk. Cache maximum option `prepareCacheLength` is then not repected, because can be up to 2x that value, leading to error when reaching server max_prepared_stmt_count. After implementation verification and benchmarking, lru-cache will be the replacement, resolving the issue in next version
