### ISSUE TITLE
sql timeouts functionality missing

### ISSUE THREAD

**Issue by mafischer** [mariadb-corporation/mariadb-connector-nodejs#81]
From original mysql driver [documentation](https://github.com/mysqljs/mysql#timeouts):
```
// Kill query after 60s
connection.query({sql: 'SELECT COUNT(*) AS count FROM big_table', timeout: 60000}, function (error, results, fields) {
  if (error && error.code === 'PROTOCOL_SEQUENCE_TIMEOUT') {
    throw new Error('too long to count table rows!');
  }

  if (error) {
    throw error;
  }

  console.log(results[0].count + ' rows');
});
```

**Comment by rusher** [comment]
Mysql implementation is just a timeout event, throwing out an error early than socket response. Problem is that the command is still executing on the server. 
You can easily saturate a server with bad long queries and timeout. 

I personally think that this is not the expected behavior of this option. 

There is 2 possibles implementation for proper query timeout
* Client-side: use another connection to execute command `KILL QUERY <threadId>`. 
* Server-side for server > 10.1.2 (and mysql >= 5.7.4)  : using `SET STATEMENT max_statement_time=<timeout> <command>` . Server will throw an error if command took longer than timeout, ending query. 

Best might be : 
- throw an error if a timeout is set and the server doesn't permit `SET STATEMENT max_statement_time` command. Error would indicate to upgrade version to have this functionality. 
- adding  `SET STATEMENT max_statement_time=xxx` to query when timeout is set.  Server would then throw an error 'Query execution was interrupted (max_statement_time exceeded)' (error code  'ER_STATEMENT_TIMEOUT')

**Comment by mafischer** [comment]
One caveat to `max_statement_time` is that it [doesn't work](https://jira.mariadb.org/browse/MDEV-18673) on galera for commits;

In my use case (using galera), the way it's implemented in [mysqljs/mysql](https://github.com/mysqljs/mysql#timeouts) seems to have performed better than using `max_statement_time`. Not sure if that's because when destroying the connection the db [rolls back](https://mariadb.com/kb/en/library/data-manipulation-kill-connection-query/#syntax) an active transaction. It could also be a false perception since I have not adequately benchmarked the difference.

**Comment by rusher** [comment]
Other limitation : 
* max_statement_time only permit second, not millisecond.
* max_statement_time is engine dependent. So there might be some differences: Galera commits works, but if the commit has been done on master during this time, replication to other nodes will be done, possibly then exceeded timeout. 
* mysql has a different implementation: it permits millisecond, but only works for SELECT queries. 

In fact, using max_statement_time behaviour is equivalent to using KILL QUERY <connection id>. The main advantage is not needing another connection to execute this command. 

I still consider implementing `max_statement_time` the best option to handle timeout. 
Timeout set on connection options level would set session max_statement_time, 
and query can have a specific timeout that would use SET STATEMENT <timeout> FOR <query>

**Comment by rusher** [comment]
Version 2.2.0 is out with timeout implementation discussed here.

This is limited to MariaDB server >= 10.1.2 

See [documentation](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#timeout)

So i'm closing this issue, but feel free to create one if new possible addition
